name: Sonar Analysis
on:
  push:
    branches:
      - develop
  pull_request:
jobs:
  build:
    name: Analyse Module with SonarCloud
    uses: exoplatform/swf-scripts/.github/workflows/sonarcloud.yml@master
    with:
      jdk_major_version: 17
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}