name: Meeds Builders PR Task Webhook

on:
  pull_request:
    types: [opened, reopened, closed, review_requested]
  pull_request_review:
    types: [submitted]

jobs:
  check_tasks:
    name: Check for Meeds Builders tasks identifiers
    uses: exoplatform/swf-scripts/.github/workflows/ghawebhooktasks.yml@master
    with:
      TARGET_SERVER: 'builders'
    secrets:
      SERVER_USERNAME: ${{ secrets.BUILDERS_USERNAME }}
      SERVER_PASSWORD: ${{ secrets.BUILDERS_PASSWORD }}
      SERVER_TASK_REST_PREFIXE_URL: ${{ secrets.BUILDERS_TASK_REST_PREFIXE_URL }}
      SERVER_GAMGH_CONNECTOR_REST_URL: ${{ secrets.BUILDERS_GAMGH_CONNECTOR_REST_URL }}