name: Crowdin Upload main

on:
  workflow_dispatch:
  push:
    branches:
      - develop
jobs:
  crowdin-upload-main:
    name: Crowdin Upload main
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - name: Crowdin Upload
        uses: exo-actions/crowdin-upload-action@v1
        with:
          YML_CROWDIN_LANGUAGES_ARG: ${{ vars.YML_CROWDIN_LANGUAGES_ARG }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
