name: PLF PR Task Webhook

on:
  pull_request:
    types: [opened, reopened, closed, review_requested]
  pull_request_review:
    types: [submitted]

jobs:
  check_tasks:
    name: Check for PLF tasks identifiers
    uses: exoplatform/swf-scripts/.github/workflows/ghawebhooktasks.yml@master
    strategy:
      matrix:
        include:
          - TARGET_SERVER: builders
            SERVER_USERNAME: BUILDERS_USERNAME
            SERVER_PASSWORD: BUILDERS_PASSWORD
            SERVER_TASK_REST_PREFIXE_URL: BUILDERS_TASK_REST_PREFIXE_URL
            SERVER_GAMGH_CONNECTOR_REST_URL: BUILDERS_GAMGH_CONNECTOR_REST_URL
          - TARGET_SERVER: tribe
            SERVER_USERNAME: TRIBE_USERNAME
            SERVER_PASSWORD: TRIBE_PASSWORD
            SERVER_TASK_REST_PREFIXE_URL: TRIBE_TASK_REST_PREFIXE_URL
            SERVER_GAMGH_CONNECTOR_REST_URL: TRIBE_GAMGH_CONNECTOR_REST_URL
    with:
      TARGET_SERVER: ${{ matrix.TARGET_SERVER }}
    secrets:
      SERVER_USERNAME: ${{ secrets[matrix.SERVER_USERNAME] }}
      SERVER_PASSWORD: ${{ secrets[matrix.SERVER_PASSWORD] }}
      SERVER_TASK_REST_PREFIXE_URL: ${{ secrets[matrix.SERVER_TASK_REST_PREFIXE_URL] }}
      SERVER_GAMGH_CONNECTOR_REST_URL: ${{ secrets[matrix.SERVER_GAMGH_CONNECTOR_REST_URL] }}